// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: grades.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grades_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{0}
}

type IdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grades_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{1}
}

func (x *IdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GradeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Grade *Grade `protobuf:"bytes,2,opt,name=grade,proto3" json:"grade,omitempty"`
}

func (x *GradeRequest) Reset() {
	*x = GradeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grades_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRequest) ProtoMessage() {}

func (x *GradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRequest.ProtoReflect.Descriptor instead.
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{2}
}

func (x *GradeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GradeRequest) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

type Grade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type  string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Score float32 `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Grade) Reset() {
	*x = Grade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grades_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{3}
}

func (x *Grade) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Grade) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Grade) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Grades    []*Grade `protobuf:"bytes,4,rep,name=grades,proto3" json:"grades,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grades_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{4}
}

func (x *Student) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Student) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Student) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Student) GetGrades() []*Grade {
	if x != nil {
		return x.Grades
	}
	return nil
}

type StudentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	//错误信息
	Msg  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *Student `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StudentReply) Reset() {
	*x = StudentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grades_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentReply) ProtoMessage() {}

func (x *StudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentReply.ProtoReflect.Descriptor instead.
func (*StudentReply) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{5}
}

func (x *StudentReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StudentReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StudentReply) GetData() *Student {
	if x != nil {
		return x.Data
	}
	return nil
}

type StudentsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	//错误信息
	Msg  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*Student `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *StudentsReply) Reset() {
	*x = StudentsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grades_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentsReply) ProtoMessage() {}

func (x *StudentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentsReply.ProtoReflect.Descriptor instead.
func (*StudentsReply) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{6}
}

func (x *StudentsReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StudentsReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StudentsReply) GetData() []*Student {
	if x != nil {
		return x.Data
	}
	return nil
}

type GradesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	//错误信息
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *Grade `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GradesReply) Reset() {
	*x = GradesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grades_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradesReply) ProtoMessage() {}

func (x *GradesReply) ProtoReflect() protoreflect.Message {
	mi := &file_grades_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradesReply.ProtoReflect.Descriptor instead.
func (*GradesReply) Descriptor() ([]byte, []int) {
	return file_grades_proto_rawDescGZIP(), []int{7}
}

func (x *GradesReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GradesReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GradesReply) GetData() *Grade {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grades_proto protoreflect.FileDescriptor

var file_grades_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x09, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3f, 0x0a, 0x0c, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x22, 0x47, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x76, 0x0a, 0x07, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x06, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x06, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x73, 0x22, 0x55, 0x0a, 0x0c, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x56, 0x0a, 0x0d, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x52, 0x0a, 0x0b, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xae, 0x01, 0x0a, 0x0d, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x32, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grades_proto_rawDescOnce sync.Once
	file_grades_proto_rawDescData = file_grades_proto_rawDesc
)

func file_grades_proto_rawDescGZIP() []byte {
	file_grades_proto_rawDescOnce.Do(func() {
		file_grades_proto_rawDescData = protoimpl.X.CompressGZIP(file_grades_proto_rawDescData)
	})
	return file_grades_proto_rawDescData
}

var file_grades_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grades_proto_goTypes = []interface{}{
	(*GetAllRequest)(nil), // 0: pb.GetAllRequest
	(*IdRequest)(nil),     // 1: pb.IdRequest
	(*GradeRequest)(nil),  // 2: pb.GradeRequest
	(*Grade)(nil),         // 3: pb.Grade
	(*Student)(nil),       // 4: pb.Student
	(*StudentReply)(nil),  // 5: pb.StudentReply
	(*StudentsReply)(nil), // 6: pb.StudentsReply
	(*GradesReply)(nil),   // 7: pb.GradesReply
}
var file_grades_proto_depIdxs = []int32{
	3, // 0: pb.GradeRequest.grade:type_name -> pb.Grade
	3, // 1: pb.Student.grades:type_name -> pb.Grade
	4, // 2: pb.StudentReply.data:type_name -> pb.Student
	4, // 3: pb.StudentsReply.data:type_name -> pb.Student
	3, // 4: pb.GradesReply.data:type_name -> pb.Grade
	0, // 5: pb.GradesService.GetAllStudents:input_type -> pb.GetAllRequest
	1, // 6: pb.GradesService.GetOneStudent:input_type -> pb.IdRequest
	2, // 7: pb.GradesService.AddGrade:input_type -> pb.GradeRequest
	6, // 8: pb.GradesService.GetAllStudents:output_type -> pb.StudentsReply
	5, // 9: pb.GradesService.GetOneStudent:output_type -> pb.StudentReply
	7, // 10: pb.GradesService.AddGrade:output_type -> pb.GradesReply
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_grades_proto_init() }
func file_grades_proto_init() {
	if File_grades_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grades_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grades_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grades_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grades_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Grade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grades_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grades_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grades_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grades_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grades_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grades_proto_goTypes,
		DependencyIndexes: file_grades_proto_depIdxs,
		MessageInfos:      file_grades_proto_msgTypes,
	}.Build()
	File_grades_proto = out.File
	file_grades_proto_rawDesc = nil
	file_grades_proto_goTypes = nil
	file_grades_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GradesServiceClient is the client API for GradesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GradesServiceClient interface {
	GetAllStudents(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*StudentsReply, error)
	GetOneStudent(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StudentReply, error)
	AddGrade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradesReply, error)
}

type gradesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGradesServiceClient(cc grpc.ClientConnInterface) GradesServiceClient {
	return &gradesServiceClient{cc}
}

func (c *gradesServiceClient) GetAllStudents(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*StudentsReply, error) {
	out := new(StudentsReply)
	err := c.cc.Invoke(ctx, "/pb.GradesService/GetAllStudents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradesServiceClient) GetOneStudent(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StudentReply, error) {
	out := new(StudentReply)
	err := c.cc.Invoke(ctx, "/pb.GradesService/GetOneStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradesServiceClient) AddGrade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradesReply, error) {
	out := new(GradesReply)
	err := c.cc.Invoke(ctx, "/pb.GradesService/AddGrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradesServiceServer is the server API for GradesService service.
type GradesServiceServer interface {
	GetAllStudents(context.Context, *GetAllRequest) (*StudentsReply, error)
	GetOneStudent(context.Context, *IdRequest) (*StudentReply, error)
	AddGrade(context.Context, *GradeRequest) (*GradesReply, error)
}

// UnimplementedGradesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGradesServiceServer struct {
}

func (*UnimplementedGradesServiceServer) GetAllStudents(context.Context, *GetAllRequest) (*StudentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStudents not implemented")
}
func (*UnimplementedGradesServiceServer) GetOneStudent(context.Context, *IdRequest) (*StudentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneStudent not implemented")
}
func (*UnimplementedGradesServiceServer) AddGrade(context.Context, *GradeRequest) (*GradesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGrade not implemented")
}

func RegisterGradesServiceServer(s *grpc.Server, srv GradesServiceServer) {
	s.RegisterService(&_GradesService_serviceDesc, srv)
}

func _GradesService_GetAllStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).GetAllStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GradesService/GetAllStudents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).GetAllStudents(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradesService_GetOneStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).GetOneStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GradesService/GetOneStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).GetOneStudent(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradesService_AddGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).AddGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GradesService/AddGrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).AddGrade(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GradesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GradesService",
	HandlerType: (*GradesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllStudents",
			Handler:    _GradesService_GetAllStudents_Handler,
		},
		{
			MethodName: "GetOneStudent",
			Handler:    _GradesService_GetOneStudent_Handler,
		},
		{
			MethodName: "AddGrade",
			Handler:    _GradesService_AddGrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grades.proto",
}
